-- Initial schema for JIIT Toppers. IDs are generated by Prisma (cuid).
CREATE TYPE "DataTrust" AS ENUM ('OFFICIAL','VERIFIED','COMMUNITY','DEMO');
CREATE TYPE "UserRole" AS ENUM ('STUDENT','MODERATOR','ADMIN');
CREATE TYPE "ResourceType" AS ENUM ('NOTE','PYQ','ASSIGNMENT','TUTORIAL','LAB','BOOK','VIDEO','CHEAT_SHEET','OTHER');
CREATE TYPE "ResourceStatus" AS ENUM ('PENDING','APPROVED','REJECTED','REMOVED');
CREATE TYPE "ExamType" AS ENUM ('T1','T2','T3','MIDTERM','END_SEM','QUIZ','LAB','OTHER');
CREATE TYPE "AnnouncementStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');

CREATE TABLE "Campus" (
"id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "code" TEXT NOT NULL UNIQUE,
"isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE TABLE "Branch" (
"id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "code" TEXT NOT NULL UNIQUE,
"isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE TABLE "User" (
"id" TEXT PRIMARY KEY, "authProviderId" TEXT UNIQUE, "email" TEXT NOT NULL UNIQUE, "name" TEXT,
"role" "UserRole" NOT NULL DEFAULT 'STUDENT', "campusId" TEXT, "branchId" TEXT, "admissionYear" INTEGER,
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "User_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "User_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "Curriculum" (
"id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "admissionYear" INTEGER NOT NULL, "programme" TEXT NOT NULL DEFAULT 'B.Tech',
"branchId" TEXT NOT NULL, "version" TEXT NOT NULL, "sourceUrl" TEXT, "sourceCheckedAt" TIMESTAMP(3),
"trust" "DataTrust" NOT NULL DEFAULT 'COMMUNITY', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "Curriculum_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT "Curriculum_branchId_admissionYear_version_key" UNIQUE ("branchId","admissionYear","version")
);
CREATE TABLE "Subject" (
"id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "description" TEXT,
"credits" DECIMAL(4,1), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE TABLE "CurriculumSubject" (
"id" TEXT PRIMARY KEY, "curriculumId" TEXT NOT NULL, "subjectId" TEXT NOT NULL, "semester" INTEGER NOT NULL,
"isElective" BOOLEAN NOT NULL DEFAULT false,
CONSTRAINT "CurriculumSubject_curriculumId_fkey" FOREIGN KEY ("curriculumId") REFERENCES "Curriculum"("id") ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "CurriculumSubject_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT "CurriculumSubject_curriculumId_subjectId_key" UNIQUE ("curriculumId","subjectId")
);
CREATE TABLE "Resource" (
"id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT, "type" "ResourceType" NOT NULL,
"status" "ResourceStatus" NOT NULL DEFAULT 'PENDING', "trust" "DataTrust" NOT NULL DEFAULT 'COMMUNITY',
"sourceUrl" TEXT, "storageKey" TEXT, "originalName" TEXT, "mimeType" TEXT, "sizeBytes" BIGINT,
"academicYear" INTEGER, "examType" "ExamType", "subjectId" TEXT, "campusId" TEXT, "uploaderId" TEXT,
"reviewerId" TEXT, "reviewedAt" TIMESTAMP(3), "rejectionNote" TEXT, "sourceCheckedAt" TIMESTAMP(3),
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "Resource_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "Resource_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "Resource_uploaderId_fkey" FOREIGN KEY ("uploaderId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "Resource_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "Exam" (
"id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "type" "ExamType" NOT NULL, "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3),
"room" TEXT, "syllabus" TEXT, "sourceUrl" TEXT, "sourceCheckedAt" TIMESTAMP(3),
"trust" "DataTrust" NOT NULL DEFAULT 'COMMUNITY', "subjectId" TEXT,
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "Exam_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "Company" (
"id" TEXT PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "websiteUrl" TEXT, "description" TEXT, "sourceUrl" TEXT,
"sourceCheckedAt" TIMESTAMP(3), "trust" "DataTrust" NOT NULL DEFAULT 'COMMUNITY',
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE TABLE "PlacementExperience" (
"id" TEXT PRIMARY KEY, "companyId" TEXT NOT NULL, "authorId" TEXT, "title" TEXT NOT NULL, "content" TEXT NOT NULL,
"trust" "DataTrust" NOT NULL DEFAULT 'COMMUNITY', "isApproved" BOOLEAN NOT NULL DEFAULT false,
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "PlacementExperience_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "PlacementExperience_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "Announcement" (
"id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "content" TEXT NOT NULL, "sourceUrl" TEXT, "sourceCheckedAt" TIMESTAMP(3),
"trust" "DataTrust" NOT NULL DEFAULT 'OFFICIAL', "status" "AnnouncementStatus" NOT NULL DEFAULT 'DRAFT',
"publishedAt" TIMESTAMP(3), "campusId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "Announcement_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "CampusEvent" (
"id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT, "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3),
"venue" TEXT, "sourceUrl" TEXT, "trust" "DataTrust" NOT NULL DEFAULT 'COMMUNITY', "campusId" TEXT,
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "CampusEvent_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "Discussion" (
"id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "authorId" TEXT, "isHidden" BOOLEAN NOT NULL DEFAULT false,
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "Discussion_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "DiscussionReply" (
"id" TEXT PRIMARY KEY, "discussionId" TEXT NOT NULL, "authorId" TEXT, "body" TEXT NOT NULL, "isHidden" BOOLEAN NOT NULL DEFAULT false,
"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
CONSTRAINT "DiscussionReply_discussionId_fkey" FOREIGN KEY ("discussionId") REFERENCES "Discussion"("id") ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "DiscussionReply_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "AuditEvent" (
"id" TEXT PRIMARY KEY, "actorId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL,
"metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT "AuditEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX "User_campusId_branchId_admissionYear_idx" ON "User"("campusId","branchId","admissionYear");
CREATE INDEX "User_role_idx" ON "User"("role");
CREATE INDEX "Curriculum_admissionYear_branchId_idx" ON "Curriculum"("admissionYear","branchId");
CREATE INDEX "Subject_code_idx" ON "Subject"("code");
CREATE INDEX "Subject_name_idx" ON "Subject"("name");
CREATE INDEX "CurriculumSubject_curriculumId_semester_idx" ON "CurriculumSubject"("curriculumId","semester");
CREATE INDEX "Resource_subjectId_type_status_idx" ON "Resource"("subjectId","type","status");
CREATE INDEX "Resource_trust_status_idx" ON "Resource"("trust","status");
CREATE INDEX "Resource_campusId_createdAt_idx" ON "Resource"("campusId","createdAt");
CREATE INDEX "Resource_uploaderId_createdAt_idx" ON "Resource"("uploaderId","createdAt");
CREATE INDEX "Exam_startsAt_type_idx" ON "Exam"("startsAt","type");
CREATE INDEX "Exam_subjectId_startsAt_idx" ON "Exam"("subjectId","startsAt");
CREATE INDEX "PlacementExperience_companyId_isApproved_createdAt_idx" ON "PlacementExperience"("companyId","isApproved","createdAt");
CREATE INDEX "Announcement_status_publishedAt_idx" ON "Announcement"("status","publishedAt");
CREATE INDEX "Announcement_campusId_publishedAt_idx" ON "Announcement"("campusId","publishedAt");
CREATE INDEX "CampusEvent_campusId_startsAt_idx" ON "CampusEvent"("campusId","startsAt");
CREATE INDEX "Discussion_isHidden_createdAt_idx" ON "Discussion"("isHidden","createdAt");
CREATE INDEX "DiscussionReply_discussionId_isHidden_createdAt_idx" ON "DiscussionReply"("discussionId","isHidden","createdAt");
CREATE INDEX "AuditEvent_entityType_entityId_createdAt_idx" ON "AuditEvent"("entityType","entityId","createdAt");
CREATE INDEX "AuditEvent_actorId_createdAt_idx" ON "AuditEvent"("actorId","createdAt");
